/**
 * WM-02, WM-03, WM-06 — the generated contract is true, current, and cannot
 * rot silently (W-1).
 *
 * `openapi.yaml` is what a backend developer builds against without reading
 * the app, the same way `CODEMAP.md` is what an agent reads instead of the
 * source. The failure that matters is not "the file is missing" — it is "the
 * file is confidently wrong", so the checks here are about agreement between
 * the document and the three things it is generated from, not about its
 * existence.
 *
 * Deliberately NOT derived from the thing checked (hard rule 11): the route
 * expectations come from importing `ROUTES` the way the app does, and are
 * compared against the YAML as text-parsed by the tools. The walker cases are
 * hand-written inputs with hand-written expected schemas — if they were
 * generated by the walker they would assert only that it is deterministic.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { ROUTES } from "@/data/routes";

const root = join(__dirname, "..", "..");
const repo = join(root, "..");

const run = (args: string[], cwd = root) => execFileSync(process.execPath, args, { cwd, encoding: "utf8" });
const tool = (name: string, ...args: string[]) => run([join(root, "tools", name), ...args]);
const readYaml = () => readFileSync(join(root, "openapi.yaml"), "utf8");

/** The tools are ESM `.mjs` and Jest's CommonJS transform will not take
 * them, so the document is parsed by the real reader in a child process —
 * which is also how the board runs it. `pathToFileURL` because a bare
 * Windows path is not a URL the ESM loader accepts. */
function parsedDocument(): Record<string, never> {
  const yamlUrl = pathToFileURL(join(root, "tools", "yaml.mjs")).href;
  const target = join(root, "openapi.yaml");
  const script = [
    `const Y = await import(${JSON.stringify(yamlUrl)});`,
    `const fs = await import("node:fs");`,
    `console.log(JSON.stringify(Y.parse(fs.readFileSync(${JSON.stringify(target)}, "utf8"))));`,
  ].join("");
  return JSON.parse(run(["--input-type=module", "-e", script]));
}

let cached: any = null;
const doc = () => (cached ??= parsedDocument());

type Operation = {
  operationId: string;
  parameters?: { name: string; in: string; required?: boolean }[];
  requestBody?: { content: Record<string, { schema: unknown; example?: unknown }> };
  responses: Record<string, { content?: Record<string, { schema?: unknown; example?: unknown }> }>;
};

describe("WM-03 · openapi.yaml is generated, current and complete", () => {
  it("regenerating it changes nothing", () => {
    // No sha and no date live in this document, on purpose (B-14): drift is
    // plain equality, with nothing to normalise away first.
    const tmp = join(tmpdir(), `openapi-drift-${process.pid}.yaml`);
    try {
      tool("gen-openapi.mjs", "--out", tmp);
      expect(readFileSync(tmp, "utf8")).toBe(readYaml());
    } finally {
      try {
        rmSync(tmp, { force: true });
      } catch {
        // a leftover temp file is harmless
      }
    }
  });

  it("tools/validate-openapi.mjs passes", () => {
    // the whole checker, as the board runs it — structure, every route
    // present, every $ref resolvable, every example valid against its schema
    expect(tool("validate-openapi.mjs")).toContain("valid");
  });

  it("the tools' plain-text reader sees exactly the routes TypeScript sees", () => {
    // The guard for the bug this row hit twice. `data/routes.ts` is read as
    // text by three tools, and both a greedy regex (`{ name: … [^}]* }` stops
    // at the brace in `/actions/{id}`) and a column-order regex (gen-wiring
    // required handler and group to be adjacent) read a SUBSET silently and
    // wrote a smaller map. Comparing against the imported array is the only
    // expectation that cannot be fooled the same way.
    const paths = doc().paths as unknown as Record<string, Record<string, Operation>>;
    const names = Object.values(paths).flatMap((p) => Object.values(p).map((o) => o.operationId)).sort();
    expect(names).toEqual([...ROUTES].map((r) => r.name).sort());
    expect(names.length).toBe(ROUTES.length);
  });

  it("every route has its own path item, with the right method and parameters", () => {
    const paths = doc().paths as unknown as Record<string, Record<string, Operation>>;
    const missing: string[] = [];
    const wrongParams: string[] = [];
    for (const route of ROUTES) {
      const operation = paths[route.path]?.[route.method.toLowerCase()];
      if (operation == null) {
        missing.push(`${route.method} ${route.path}`);
        continue;
      }
      const wanted = [...route.path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
      const declared = (operation.parameters ?? []).filter((p) => p.in === "path").map((p) => p.name);
      if (wanted.join(",") !== declared.join(",")) wrongParams.push(`${route.method} ${route.path}`);
    }
    expect(missing).toEqual([]);
    expect(wrongParams).toEqual([]);
  });

  it("every path has a response schema and one example, and a request schema wherever the table declares a body", () => {
    const paths = doc().paths as unknown as Record<string, Record<string, Operation>>;
    const noResponseSchema: string[] = [];
    const noExample: string[] = [];
    const noRequestSchema: string[] = [];
    for (const route of ROUTES) {
      const key = `${route.method} ${route.path}`;
      const operation = paths[route.path][route.method.toLowerCase()];

      if (route.body != null && operation.requestBody?.content?.["application/json"]?.schema == null) noRequestSchema.push(key);

      if (route.response === "NoContent") {
        expect(Object.keys(operation.responses)).toContain("204");
        continue;
      }
      const media = Object.values(operation.responses)[0]?.content?.["application/json"];
      if (media?.schema == null) noResponseSchema.push(key);
      if (media?.example === undefined) noExample.push(key);
    }
    expect(noRequestSchema).toEqual([]);
    expect(noResponseSchema).toEqual([]);
    expect(noExample).toEqual([]);
  });

  it("no mock-only route is published", () => {
    // rule 5: the test rig and the Telegram mirror exist in the mock server
    // and must never appear in the contract a backend is built from
    const paths = Object.keys(doc().paths as unknown as Record<string, unknown>);
    expect(paths.filter((p) => p.startsWith("/__"))).toEqual([]);
  });
});

describe("WM-02 · WIRING.html is the map as a picture, and opens offline", () => {
  const html = () => readFileSync(join(root, "WIRING.html"), "utf8");

  it("regenerating it changes nothing", () => {
    const tmp = join(tmpdir(), `wiring-drift-${process.pid}.html`);
    try {
      tool("gen-wiring-html.mjs", "--out", tmp);
      expect(readFileSync(tmp, "utf8")).toBe(html());
    } finally {
      try {
        rmSync(tmp, { force: true });
      } catch {
        // a leftover temp file is harmless
      }
    }
  });

  it("one diagram per contract section, named by the section", () => {
    // the expectation is wiring.json's groups, not a count read off the HTML
    const wiring = JSON.parse(readFileSync(join(root, "wiring.json"), "utf8")) as { routes: { group: string }[] };
    const groups = [...new Set(wiring.routes.map((r) => r.group))].sort();
    const src = html();
    const drawn = [...src.matchAll(/<svg [^>]*aria-label="([a-z]+) wiring"/g)].map((m) => m[1]).sort();
    expect(drawn).toEqual(groups);
    expect(drawn.length).toBeGreaterThan(5); // else this asserts nothing
  });

  it("asks for nothing off this machine", () => {
    // the file has to open from disk on a laptop with no connection — an
    // embedded Mermaid runtime or a webfont would break exactly that, and
    // would break it silently on the machine that has a connection
    const src = html();
    expect(src).not.toMatch(/https?:\/\//);
    expect(src).not.toMatch(/<script/i);
    expect(src).not.toMatch(/@import/);
    expect(src).not.toMatch(/src\s*=\s*"(?!data:)/i);
  });

  it("every diagram carries its Mermaid source too", () => {
    const src = html();
    expect([...src.matchAll(/flowchart LR/g)].length).toBe([...src.matchAll(/<svg /g)].length);
  });
});

describe("WM-06 · CONTRACT_MAP.md is both contracts' §6, and nothing else", () => {
  /** The data rows of every markdown table in a block, header and rule out. */
  function tableRows(markdown: string): string[] {
    return markdown
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.startsWith("| ") && !l.startsWith("|---") && !l.startsWith("| Endpoint") && !l.startsWith("| ID "));
  }

  function sectionSix(file: string, endMarker: string): string[] {
    const src = readFileSync(join(repo, file), "utf8");
    const start = src.indexOf("## §6");
    expect(start).toBeGreaterThan(-1);
    const end = src.indexOf(endMarker, start);
    return tableRows(src.slice(start, end === -1 ? undefined : end));
  }

  it("carries all three contracts' §6, in version order", () => {
    // A4-08/A4-05: this used to name TWO contracts while three existed, so
    // `CONTRACT_MAP.md` — whose own first line says a backend developer should
    // start HERE — held not one V2.2 row, and the guard titled "and nothing
    // else" could not notice. Every endpoint family V2.2 added was missing
    // from the one table it is read out of: parameters, the task verbs,
    // columns, slicers, usage, files, search, replies, goals, habits, the
    // agent issues and the autonomy rules.
    const expected = [...sectionSix("history/v2/CONTRACT_v2.md", "## §7"), ...sectionSix("history/v21/CONTRACT_v21.md", "## §7"), ...sectionSix("history/v22/CONTRACT_v22.md", "## §7")];
    expect(expected.length).toBeGreaterThan(25); // else this asserts nothing
    expect(tableRows(readFileSync(join(repo, "CONTRACT_MAP.md"), "utf8"))).toEqual(expected);
  });
});

describe("WM-03 · the type walker reads what CONTRACT §3 actually writes", () => {
  /**
   * Hand-written input, hand-written expected schema. A case generated by
   * running the walker would assert only that it is deterministic, which is
   * not the property that matters here (hard rule 11).
   */
  function schemaOf(declarations: Record<string, string>, name: string): unknown {
    const walkerUrl = pathToFileURL(join(root, "tools", "type-walker.mjs")).href;
    const script = [
      `const W = await import(${JSON.stringify(walkerUrl)});`,
      `const decls = new Map(Object.entries(${JSON.stringify(declarations)}));`,
      `const reg = new W.Registry(decls);`,
      `console.log(JSON.stringify(reg.schemaFor(${JSON.stringify(name)})));`,
    ].join("");
    return JSON.parse(run(["--input-type=module", "-e", script]));
  }

  it("objects, optionals and required", () => {
    expect(schemaOf({ X: "{ a: string; b?: number }" }, "X")).toEqual({
      type: "object",
      properties: { a: { type: "string" }, b: { type: "number" } },
      required: ["a"],
    });
  });

  it("a union of string literals is an enum, not a oneOf", () => {
    expect(schemaOf({ X: '"open" | "done"' }, "X")).toEqual({ type: "string", enum: ["open", "done"] });
  });

  it("arrays and references", () => {
    expect(schemaOf({ X: "Y[]", Y: "{ id: string }" }, "X")).toEqual({
      type: "array",
      items: { $ref: "#/components/schemas/Y" },
    });
  });

  it("an intersection keeps the named half named", () => {
    expect(schemaOf({ X: "Y & { b: string }", Y: "{ a: string }" }, "X")).toEqual({
      allOf: [{ $ref: "#/components/schemas/Y" }, { type: "object", properties: { b: { type: "string" } }, required: ["b"] }],
    });
  });

  it("`string | null` is nullable, not a union of two types", () => {
    expect(schemaOf({ X: "{ undone: string | null }" }, "X")).toEqual({
      type: "object",
      properties: { undone: { type: "string", nullable: true } },
      required: ["undone"],
    });
  });

  it("a tuple keeps its length, which is the part that means something", () => {
    expect(schemaOf({ X: "[Y, Y, Y]", Y: "{ a: string }" }, "X")).toEqual({
      type: "array",
      items: { $ref: "#/components/schemas/Y" },
      minItems: 3,
      maxItems: 3,
    });
  });

  it("Partial makes every property optional", () => {
    expect(schemaOf({ X: "Partial<Y>", Y: "{ a: string; b: number }" }, "X")).toEqual({
      type: "object",
      properties: { a: { type: "string" }, b: { type: "number" } },
    });
  });

  it("Omit drops the named properties", () => {
    expect(schemaOf({ X: 'Omit<Y, "b">', Y: "{ a: string; b: number }" }, "X")).toEqual({
      type: "object",
      properties: { a: { type: "string" } },
      required: ["a"],
    });
  });

  it("Record becomes additionalProperties", () => {
    expect(schemaOf({ X: "Record<string, number>" }, "X")).toEqual({
      type: "object",
      additionalProperties: { type: "number" },
    });
  });

  it("an indexed access resolves to the property's own type", () => {
    expect(schemaOf({ X: '{ owner: Y["owner"] }', Y: '{ owner: "josh" | "joce" }' }, "X")).toEqual({
      type: "object",
      properties: { owner: { type: "string", enum: ["josh", "joce"] } },
      required: ["owner"],
    });
  });

  it("a shape it cannot read throws, naming it — it never emits an empty schema", () => {
    // the failure mode this walker exists to avoid: a type it did not
    // understand becoming `{}`, which validates against anything and puts a
    // lie in the document a backend is built from
    expect(() => schemaOf({ X: "keyof Y", Y: "{ a: string }" }, "X")).toThrow();
    expect(() => schemaOf({ X: "Uppercase<Y>", Y: "string" }, "X")).toThrow();
  });
});

describe("WM-03 · the shape registry and the type file stay in step", () => {
  it("Shapes lists exactly the non-generic exported types of data/types.ts", () => {
    // `keyof Shapes` is what makes a bad route column a `pnpm check` error, so
    // a shape added without a registry line would silently be unnameable
    const src = readFileSync(join(root, "data", "types.ts"), "utf8");
    const registry = src.slice(src.indexOf("export type Shapes = {"));
    const listed = [...registry.matchAll(/^ {2}([A-Za-z0-9_]+): [A-Za-z0-9_]+;$/gm)].map((m) => m[1]).sort();

    const declared = [...src.matchAll(/^export type ([A-Za-z0-9_]+)(<[^=]*>)?\s*=/gm)]
      .filter((m) => m[2] == null)
      .map((m) => m[1])
      .filter((n) => n !== "Shapes" && n !== "ShapeName")
      .sort();

    expect(declared.length).toBeGreaterThan(100); // else this asserts nothing
    expect(listed).toEqual(declared);
  });

  it("every shape a route names is one the walker can actually read", () => {
    // ROUTES is the expectation; the walker is what is being checked
    const named = [...new Set(ROUTES.flatMap((r) => [r.response, r.body]).filter(Boolean))] as string[];
    expect(named.length).toBeGreaterThan(50);
    const schemas = doc().components as unknown as { schemas: Record<string, unknown> };
    expect(named.filter((n) => schemas.schemas[n] === undefined)).toEqual([]);
  });
});

describe("WPF-5 · what a backend generates from is what the app puts on the wire", () => {
  it("the upload publishes its multipart body, and every offline route's JSON body declares offlineId", () => {
    const post = (doc().paths as Record<string, Record<string, Operation>>)["/files"].post;
    expect(Object.keys(post.requestBody?.content ?? {})).toEqual(["multipart/form-data"]);

    // the outbox puts the id on every one of these bodies (data/transport/outbox.ts)
    const schemas = (doc().components as unknown as { schemas: Record<string, unknown> }).schemas;
    const bodies = ROUTES.filter((r) => r.offline === true && r.body != null).map((r) => r.body as string);
    expect(bodies).toHaveLength(9);
    expect(bodies.filter((name) => !JSON.stringify(schemas[name]).includes('"offlineId"'))).toEqual([]);
  });
});
