/**
 * Generates `openapi.yaml` from the three things that already know the truth
 * (W-1, WM-03): `data/routes.ts` (every endpoint, once), `data/types.ts` (the
 * wire shapes those routes name in their `body`/`response` columns) and
 * `data/mock/fixtures/*.json` (real records, for the examples).
 *
 * Nothing here is hand-maintained, which is the point. A hand-written OpenAPI
 * document beside a running app is a second source of truth that starts
 * drifting the day it is written; this one is regenerated by the pre-commit
 * hook and checked by `tests/unit/openapi.test.ts`, so it is either current or
 * the board is red.
 *
 * Three rules it holds itself to:
 *
 *  1. **Every example is valid against the schema printed beside it.** The
 *     example is the part a developer copies. A fixture is tried first — that
 *     is "an example from the fixture the handler reads" — and it is only
 *     used if it actually satisfies the schema; otherwise a minimal example is
 *     synthesised from the schema itself. Validation is the test, not a
 *     similarity score, so a fixture that has drifted from the type cannot
 *     silently become a wrong example.
 *  2. **A shape it cannot read is an error, never an empty schema.** See
 *     `tools/type-walker.mjs`.
 *  3. **Reproducible, and unstamped.** Sorted keys, sorted route order by
 *     path, and no sha or date anywhere in the document. B-14 was a drift
 *     check comparing a stamp that changes on every commit; the cheapest way
 *     not to repeat it is to have nothing in the file that varies with WHEN
 *     it was generated. Git already knows. Drift is then plain equality.
 *
 * Run: `node tools/gen-openapi.mjs` (or `pnpm codemap`, which runs it in
 * order after the wiring map). `--out <path>` writes elsewhere, which is how
 * the drift test regenerates without touching the committed file.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readRoutes } from "./read-routes.mjs";
import { Registry, readDeclarations } from "./type-walker.mjs";
import { validate } from "./schema-validate.mjs";
import { dump } from "./yaml.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "openapi.yaml");

const byName = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// ─── examples ───────────────────────────────────────────────────────────

/** Every fixture value a route could plausibly be an example of: each file's
 * root, and each of its top-level collections. */
function fixtureCandidates() {
  const dir = join(root, "data", "mock", "fixtures");
  const out = [];
  for (const file of readdirSync(dir).sort(byName)) {
    if (!file.endsWith(".json")) continue;
    const stem = file.replace(/\.json$/, "");
    const value = JSON.parse(readFileSync(join(dir, file), "utf8"));
    out.push({ source: stem, stem, value });
    if (!Array.isArray(value)) {
      for (const key of Object.keys(value).sort(byName)) out.push({ source: `${stem}.${key}`, stem, value: value[key] });
    }
  }
  return out;
}

/** The property names a schema declares at its top level, following `$ref`
 * and `allOf` — used to rank candidates before validating them. */
function propertyNames(schema, schemas, depth = 0) {
  if (schema == null || depth > 6) return [];
  if (schema.$ref) return propertyNames(schemas[schema.$ref.split("/").pop()], schemas, depth + 1);
  if (schema.allOf) return schema.allOf.flatMap((s) => propertyNames(s, schemas, depth + 1));
  if (schema.type === "array") return propertyNames(schema.items, schemas, depth + 1);
  return Object.keys(schema.properties ?? {});
}

function overlap(schema, schemas, value) {
  const wanted = new Set(propertyNames(schema, schemas));
  if (wanted.size === 0) return 0;
  const sample = Array.isArray(value) ? value[0] : value;
  if (sample == null || typeof sample !== "object") return 0;
  return Object.keys(sample).filter((k) => wanted.has(k)).length;
}

/** A minimal value that satisfies the schema — required properties only. */
function synthesise(schema, schemas, seen = new Set()) {
  if (schema == null) return null;
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop();
    if (seen.has(name)) return null;
    return synthesise(schemas[name], schemas, new Set([...seen, name]));
  }
  if (schema.allOf) return Object.assign({}, ...schema.allOf.map((s) => synthesise(s, schemas, seen)));
  if (schema.oneOf) return synthesise(schema.oneOf[0], schemas, seen);
  if (schema.enum) return schema.enum[0];
  if (schema.type === "array") {
    const one = synthesise(schema.items ?? {}, schemas, seen);
    return Array.from({ length: Math.max(1, schema.minItems ?? 1) }, () => one);
  }
  if (schema.type === "object" || schema.properties) {
    const out = {};
    for (const name of schema.required ?? []) out[name] = synthesise(schema.properties?.[name] ?? {}, schemas, seen);
    return out;
  }
  if (schema.type === "string") return schema.format === "date-time" ? "2026-09-04T00:00:00.000Z" : "string";
  if (schema.type === "number" || schema.type === "integer") return 0;
  if (schema.type === "boolean") return false;
  if (schema.type === "null") return null;
  return {};
}

/**
 * The example for a response: the best-matching fixture that VALIDATES,
 * else one synthesised from the schema. A fixture from the handler's own
 * file is preferred, which is what "the fixture the handler reads" means
 * when several files could supply a record of the same shape.
 */
function exampleFor(schema, schemas, candidates, route) {
  const module = route.handler.split(".")[0];
  const ranked = candidates
    .map((c) => ({ ...c, score: overlap(schema, schemas, c.value) + (c.stem === module || c.stem === route.group ? 100 : 0) }))
    .filter((c) => c.score > 0)
    .sort((a, b) => b.score - a.score || byName(a.source, b.source));

  for (const candidate of ranked) {
    if (validate(candidate.value, schema, schemas).length === 0) return { value: candidate.value, from: candidate.source };
  }
  return { value: synthesise(schema, schemas), from: null };
}

// ─── the document ───────────────────────────────────────────────────────

const HTTP_OK = { GET: "200", POST: "200", PUT: "200", PATCH: "200", DELETE: "200" };

/** Everything reachable from the shapes the routes name, so `components`
 * carries the vocabulary and nothing it does not use. */
function reachable(names, registry) {
  const wanted = new Set();
  const queue = [...names];
  while (queue.length) {
    const name = queue.shift();
    if (wanted.has(name) || !registry.has(name)) continue;
    wanted.add(name);
    const json = JSON.stringify(registry.schemaFor(name));
    for (const match of json.matchAll(/"#\/components\/schemas\/([A-Za-z0-9_]+)"/g)) queue.push(match[1]);
  }
  return [...wanted].sort(byName);
}

function pathItem(route, schemas, candidates) {
  const operation = {
    operationId: route.name,
    summary: `${route.name} (CONTRACT ${route.marker})`,
    tags: [route.group],
  };

  const params = [...route.path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
  if (params.length) {
    operation.parameters = params.map((name) => ({
      name,
      in: "path",
      required: true,
      schema: { type: "string" },
    }));
  }

  // X-1: an upload carries a file, not a shape. The document says so rather
  // than leaving the body undeclared, which would read as "takes nothing".
  if (route.multipart) {
    operation.requestBody = {
      required: true,
      content: {
        "multipart/form-data": {
          schema: {
            type: "object",
            required: ["file"],
            properties: {
              file: { type: "string", format: "binary" },
              taskId: { type: "string" },
              subtaskId: { type: "string" },
              captureId: { type: "string" },
            },
          },
        },
      },
    };
  }

  if (route.body) {
    const schema = { $ref: `#/components/schemas/${route.body}` };
    const example = exampleFor(schema, schemas, candidates, route);
    operation.requestBody = {
      required: true,
      content: { "application/json": { schema, example: example.value } },
    };
  }

  if (route.response === "NoContent") {
    operation.responses = { "204": { description: "No content." } };
    return operation;
  }

  const schema = { $ref: `#/components/schemas/${route.response}` };
  const example = exampleFor(schema, schemas, candidates, route);
  operation.responses = {
    [HTTP_OK[route.method]]: {
      description: `${route.response}.`,
      content: { "application/json": { schema, example: example.value } },
    },
  };
  return operation;
}

function buildDocument({ routes, registry }) {
  const named = reachable(routes.flatMap((r) => [r.response, r.body]).filter(Boolean), registry);
  const schemas = {};
  for (const name of named) schemas[name] = registry.schemaFor(name);

  const candidates = fixtureCandidates();
  const paths = {};
  for (const route of [...routes].sort((a, b) => byName(a.path, b.path) || byName(a.method, b.method))) {
    paths[route.path] ??= {};
    paths[route.path][route.method.toLowerCase()] = pathItem(route, schemas, candidates);
  }

  return {
    openapi: "3.0.3",
    info: {
      title: "JSTACK",
      // the DOCUMENT's version, which is the release it describes — not the OpenAPI
      // spec version above it. It said 2.1.0 on a v2.2 tree of 135 routes until the
      // REMAP pack build read it (planner, 13 Sep): this is the file REMAP implements
      // against, so a stale number here reads as the contract's age.
      version: "2.2.0",
      description: [
        "Generated from data/routes.ts, data/types.ts and the mock fixtures by tools/gen-openapi.mjs.",
        "Do not edit by hand: the pre-commit hook regenerates it and tests/unit/openapi.test.ts fails on drift.",
      ].join(" "),
    },
    servers: [{ url: "/", description: "The backend the app is pointed at (data/config.ts)." }],
    paths,
    components: { schemas },
  };
}

// ─── assembly ───────────────────────────────────────────────────────────

function generate(outPath = OUT) {
  const source = readFileSync(join(root, "data", "routes.ts"), "utf8");
  const routes = readRoutes(source);
  // a row the reader missed is the failure this tool is least likely to
  // notice on its own, so count them two ways and compare
  const declared = source.split("\n").filter((l) => l.trim().startsWith('{ name: "')).length;
  if (routes.length !== declared) throw new Error(`gen-openapi: read ${routes.length} routes but data/routes.ts declares ${declared}`);
  if (routes.length === 0) throw new Error("gen-openapi: read no routes from data/routes.ts");
  const incomplete = routes.filter((r) => !r.method || !r.path || !r.response || !r.group);
  if (incomplete.length) throw new Error(`gen-openapi: ${incomplete.length} route row(s) missing a column: ${incomplete.map((r) => r.name).join(", ")}`);

  const declarations = new Map();
  for (const file of ["data/labels.ts", "data/types.ts"]) {
    for (const [name, text] of readDeclarations(readFileSync(join(root, file), "utf8"))) declarations.set(name, text);
  }
  const registry = new Registry(declarations);

  const doc = buildDocument({ routes, registry });

  // every example must satisfy the schema printed beside it — the generator
  // refuses to write a document whose examples lie
  const bad = [];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const [method, operation] of Object.entries(item)) {
      for (const [where, media] of [
        ["request", operation.requestBody?.content?.["application/json"]],
        ["response", Object.values(operation.responses)[0]?.content?.["application/json"]],
      ]) {
        if (media?.example === undefined) continue;
        const errors = validate(media.example, media.schema, doc.components.schemas);
        if (errors.length) bad.push(`${method.toUpperCase()} ${path} ${where}: ${errors[0].path} ${errors[0].reason}`);
      }
    }
  }
  if (bad.length) throw new Error(`gen-openapi: ${bad.length} example(s) do not match their schema:\n  ${bad.join("\n  ")}`);

  writeFileSync(outPath, dump(doc).split("\r\n").join("\n"));

  // The REQUEST half of the same document, as JSON (H-1e). The mock server
  // validates bodies at runtime the way CONTRACT §8 Q10 says a real backend
  // will, and Metro cannot import a .yaml.
  //
  // Request schemas and the shared components only — no examples, no
  // responses. The full document is 295KB and every byte of it would be in
  // the demo bundle; this is the part a validator actually reads, and it is
  // written from the same object in the same pass, so the two cannot
  // disagree.
  if (outPath === OUT) {
    const requests = {};
    for (const [path, item] of Object.entries(doc.paths)) {
      for (const [method, operation] of Object.entries(item)) {
        const schema = operation.requestBody?.content?.["application/json"]?.schema;
        if (schema == null) continue;
        requests[path] ??= {};
        requests[path][method] = schema;
      }
    }
    const slim = { requests, schemas: doc.components.schemas };
    writeFileSync(join(root, "data", "requestSchemas.json"), JSON.stringify(slim, null, 2) + "\n");
  }

  return { routes: routes.length, schemas: Object.keys(doc.components.schemas).length };
}

if (process.argv[1] && process.argv[1].endsWith("gen-openapi.mjs")) {
  const i = process.argv.indexOf("--out");
  const { routes, schemas } = generate(i === -1 ? OUT : process.argv[i + 1]);
  console.log(`openapi.yaml written: ${routes} paths, ${schemas} schemas`);
}
