#!/usr/bin/env node
/**
 * Generates components/chrome/icons.generated.ts from
 * @material-symbols/svg-300 (rounded, weight 300) for every icon name in
 * theme/tokens.ts's `iconNames` plus the mock's extras (ADR-09). Run with
 * no args to write the committed file; `--out <path>` writes elsewhere
 * (used by a Jest regenerate-and-diff test, mirroring gen-tokens.mjs).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SVG_DIR = join(ROOT, "node_modules", "@material-symbols", "svg-300", "rounded");

/** design/tokens.json's `iconName` block — read directly rather than via
 * the generated theme/tokens.ts, so this script has no runtime dependency
 * on a .ts file (mirrors tools/gen-tokens.mjs's own reading of the same
 * block). Kept in sync by tests/unit/icons.test.ts against theme/tokens.ts. */
function readIconNames() {
  const json = JSON.parse(readFileSync(join(ROOT, "design", "tokens.json"), "utf8"));
  return Object.fromEntries(Object.entries(json.iconName ?? {}).map(([k, v]) => [k, v.$value]));
}

// The mock adds a few names beyond theme/tokens.ts's semantic iconNames map
// (BUILD_PLAN_v2.md row 3). `expand_more` does not exist in this version of
// @material-symbols/svg-300 (checked across rounded/outlined/sharp) — the
// nearest equivalent glyph, `keyboard_arrow_down`, stands in for it
// (BUGLOG_v2.md A-05).
const EXTRA_NAMES = [
  "chevron_left",
  "check",
  "close",
  "edit",
  "arrow_upward",
  "arrow_downward",
  "arrow_forward",
  "keyboard_arrow_down", // stands in for expand_more (BUGLOG_v2.md A-05)
  "light_mode",
  "search",
  "keyboard",
  "mic",
  "attach_file", // X-1: the attach control on the capture field and the task card
];

function readSvg(name, fill) {
  const path = join(SVG_DIR, `${name}${fill ? "-fill" : ""}.svg`);
  const src = readFileSync(path, "utf8");
  const viewBox = /viewBox="([^"]+)"/.exec(src)?.[1];
  const ds = [...src.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!viewBox || ds.length === 0) throw new Error(`could not parse ${path}`);
  return { viewBox, d: ds.join(" ") };
}

function ts(value, indent = 0) {
  const pad = "  ".repeat(indent);
  if (typeof value === "string") return JSON.stringify(value);
  const entries = Object.entries(value)
    .map(([k, v]) => `${pad}  ${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${ts(v, indent + 1)},`)
    .join("\n");
  return `{\n${entries}\n${pad}}`;
}

function generate() {
  const iconNames = readIconNames();
  const names = [...new Set([...Object.values(iconNames), ...EXTRA_NAMES])].sort();
  const icons = {};
  for (const name of names) {
    const plain = readSvg(name, false);
    let fill;
    try {
      fill = readSvg(name, true);
    } catch {
      fill = null; // a handful of glyphs have no filled variant
    }
    icons[name] = { viewBox: plain.viewBox, d: plain.d, ...(fill ? { fillD: fill.d } : {}) };
  }

  return `/**
 * generated by tools/gen-icons.mjs from
 * node_modules/@material-symbols/svg-300/rounded — do not edit
 */

export type IconDef = { viewBox: string; d: string; fillD?: string };

export const ICONS: Record<string, IconDef> = ${ts(icons)};

export type IconName = keyof typeof ICONS;
`;
}

function main() {
  const outArgIdx = process.argv.indexOf("--out");
  const outPath = outArgIdx !== -1 ? process.argv[outArgIdx + 1] : join(ROOT, "components", "chrome", "icons.generated.ts");
  writeFileSync(outPath, generate());
  console.log(`wrote ${outPath}`);
}

main();
