/**
 * Copies the five faces the app uses out of the @expo-google-fonts packages
 * into `public/fonts/`, where Expo's web export serves them as static files
 * (S-4, SM-06/SEC-09).
 *
 * Why the files are committed rather than copied at build time: `public/` is
 * what the export ships, and a build step that reaches into `node_modules`
 * is a build step that can silently produce a different font than the one
 * that was reviewed. Committing them makes the bytes part of the diff.
 * `tests/unit/fonts.test.ts` asserts each committed file is byte-identical
 * to its package original, so a stale copy fails the board rather than
 * shipping quietly.
 *
 * SEC-09 is the reason none of this comes from Google's CDN: no third-party
 * origin serves this app anything, fonts included.
 *
 * Run: `node tools/vendor-fonts.mjs` (also `pnpm fonts`). Idempotent.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The five faces `theme/tokens.ts` names and `lib/boot.ts` loads on native.
 * `weight` is what the web `@font-face` rule declares, so `fontWeight: 500`
 * picks the Medium face rather than the browser synthesising a fake bold
 * out of the Regular — the bug DS-02 was about.
 */
export const FACES = [
  { pkg: "instrument-sans", dir: "400Regular", file: "InstrumentSans_400Regular.ttf", family: "Instrument Sans", weight: 400 },
  { pkg: "instrument-sans", dir: "500Medium", file: "InstrumentSans_500Medium.ttf", family: "Instrument Sans", weight: 500 },
  { pkg: "instrument-sans", dir: "600SemiBold", file: "InstrumentSans_600SemiBold.ttf", family: "Instrument Sans", weight: 600 },
  { pkg: "source-serif-4", dir: "400Regular", file: "SourceSerif4_400Regular.ttf", family: "Source Serif 4", weight: 400 },
  { pkg: "source-serif-4", dir: "500Medium", file: "SourceSerif4_500Medium.ttf", family: "Source Serif 4", weight: 500 },
];

const sourceOf = (f) => join(root, "node_modules", "@expo-google-fonts", f.pkg, f.dir, f.file);
export const vendoredOf = (f) => join(root, "public", "fonts", f.file);

/** The pack's body stack, from design/tokens/typography.css. */
const BODY_STACK = "'Instrument Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

/**
 * The `@font-face` block, built once and used by both consumers — the web
 * export (`build-web.mjs`, real `/fonts/…` URLs) and the single-file mock
 * (`build-mock.mjs`, data: URIs, because it has no path to serve). One list
 * of faces, one set of rules; `tests/unit/fonts.test.ts` checks both call
 * sites still go through here.
 *
 * `font-display: swap` on purpose: text renders immediately in the fallback
 * and reflows when the face lands, rather than a blank screen while a 330KB
 * serif downloads.
 *
 * The `html, body` rule is what DS-03 measures. react-native-web puts its own
 * stack (`-apple-system, …`) on a class every `<Text>` without an explicit
 * family carries, and most of this app's text sets only a size and a colour;
 * naming the body stack here is what makes Today's body text compute to
 * Instrument Sans instead of the OS UI font — the defect ux-review round 1
 * found on 127 of 129 text nodes.
 */
export function fontFaceCss(srcFor) {
  return [
    ...FACES.map(
      (f) => `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};font-display:swap;src:url("${srcFor(f)}")}`,
    ),
    `html,body{font-family:${BODY_STACK}}`,
  ].join("\n");
}

function main() {
  const outDir = join(root, "public", "fonts");
  mkdirSync(outDir, { recursive: true });

  let copied = 0;
  for (const f of FACES) {
    const src = sourceOf(f);
    if (!existsSync(src)) throw new Error(`missing font in node_modules: ${src} — run pnpm install`);
    const dest = vendoredOf(f);
    const same = existsSync(dest) && readFileSync(dest).equals(readFileSync(src));
    if (!same) {
      copyFileSync(src, dest);
      copied++;
    }
    console.log(`  ${same ? "unchanged" : "copied   "}  ${f.file}`);
  }

  // A README beside the files, because a directory of committed binaries with
  // no explanation is the kind of thing a later reader deletes.
  writeFileSync(
    join(outDir, "README.md"),
    [
      "# public/fonts",
      "",
      "Generated by `node tools/vendor-fonts.mjs` (`pnpm fonts`). Do not edit by hand.",
      "",
      "These are copied verbatim from the `@expo-google-fonts/*` packages and committed so the",
      "web export serves them from this origin — SEC-09: no third-party origin serves this app",
      "anything. `tools/build-web.mjs` injects the `@font-face` rules that point here.",
      "",
      "`tests/unit/fonts.test.ts` asserts every file here is byte-identical to its package",
      "original, so a stale copy fails the board instead of shipping quietly.",
      "",
    ].join("\n"),
  );
  console.log(`vendor-fonts: ${copied} copied, ${FACES.length - copied} already current`);
}

if (process.argv[1] && process.argv[1].endsWith("vendor-fonts.mjs")) main();
