/**
 * generated by tools/gen-tokens.mjs from design/tokens — do not edit
 * (see design/DISCREPANCIES.md for the three values this script overrides)
 */
import { Platform } from "react-native";

export type ThemeName = "light" | "dark";

export type ShadowToken = {
  css: string;
  native: { shadowColor: string; shadowOffset: { width: number; height: number }; shadowOpacity: number; shadowRadius: number; elevation: number };
};

export type Tokens = {
  ground: string;
  card: string;
  cardBorder: string;
  bar: string;
  hairline: string;
  ink: string;
  muted: string;
  accent: string;
  accentSoft: string;
  accentInk: string;
  marker: string;
  ok: string;
  warn: string;
  alert: string;
  selected: string;
  onSelected: string;
  textBody: string;
  textMeta: string;
  textLabel: string;
  textLink: string;
  textExpiry: string;
  surfacePage: string;
  surfaceCard: string;
  surfaceInset: string;
  btnPrimaryBg: string;
  btnPrimaryFg: string;
  badgeBg: string;
  badgeFg: string;
  micLive: string;
  shadow: ShadowToken;
  shadowSeg: ShadowToken;
};

export const light: Tokens = {
  ground: "#EDEBE5",
  card: "rgba(255,255,255,.58)",
  cardBorder: "rgba(255,255,255,.7)",
  bar: "rgba(255,255,255,.72)",
  hairline: "rgba(43,42,38,.08)",
  ink: "#2B2A26",
  muted: "#7A776F",
  accent: "#66798A",
  accentSoft: "rgba(102,121,138,.14)",
  accentInk: "#4A5E70",
  marker: "#4F7FA8",
  ok: "#4F8A6B",
  warn: "#96702E",
  alert: "#B0553F",
  selected: "#2B2A26",
  onSelected: "#F4F3EE",
  textBody: "#2B2A26",
  textMeta: "#7A776F",
  textLabel: "#4A5E70",
  textLink: "#4A5E70",
  textExpiry: "#4A5E70",
  surfacePage: "#EDEBE5",
  surfaceCard: "rgba(255,255,255,.58)",
  surfaceInset: "rgba(102,121,138,.14)",
  btnPrimaryBg: "rgba(102,121,138,.14)",
  btnPrimaryFg: "#4A5E70",
  badgeBg: "#4F7FA8",
  badgeFg: "#FFFFFF",
  micLive: "#4F7FA8",
  shadow: {
    css: "0 8px 22px rgba(60,55,45,.07), 0 1px 3px rgba(60,55,45,.04)",
    native: {
      shadowColor: "rgb(60, 55, 45)",
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.07,
      shadowRadius: 22,
      elevation: 7,
    },
  },
  shadowSeg: {
    css: "0 1px 3px rgba(60,55,45,.14)",
    native: {
      shadowColor: "rgb(60, 55, 45)",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.14,
      shadowRadius: 3,
      elevation: 1,
    },
  },
};

export const dark: Tokens = {
  ground: "#191815",
  card: "rgba(255,255,255,.08)",
  cardBorder: "rgba(255,255,255,.1)",
  bar: "rgba(40,38,34,.9)",
  hairline: "rgba(255,255,255,.08)",
  ink: "#ECE9E2",
  muted: "#93908A",
  accent: "#9AAEC0",
  accentSoft: "rgba(154,174,192,.16)",
  accentInk: "#B7C8D8",
  marker: "#7FA9CF",
  ok: "#7DBF9C",
  warn: "#D2B067",
  alert: "#D9785E",
  selected: "#ECE9E2",
  onSelected: "#191815",
  textBody: "#ECE9E2",
  textMeta: "#93908A",
  textLabel: "#B7C8D8",
  textLink: "#B7C8D8",
  textExpiry: "#B7C8D8",
  surfacePage: "#191815",
  surfaceCard: "rgba(255,255,255,.08)",
  surfaceInset: "rgba(154,174,192,.16)",
  btnPrimaryBg: "rgba(154,174,192,.16)",
  btnPrimaryFg: "#B7C8D8",
  badgeBg: "#7FA9CF",
  badgeFg: "#FFFFFF",
  micLive: "#7FA9CF",
  shadow: {
    css: "0 12px 30px rgba(0,0,0,.45)",
    native: {
      shadowColor: "rgb(0, 0, 0)",
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.45,
      shadowRadius: 30,
      elevation: 10,
    },
  },
  shadowSeg: {
    css: "0 1px 3px rgba(0,0,0,.4)",
    native: {
      shadowColor: "rgb(0, 0, 0)",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.4,
      shadowRadius: 3,
      elevation: 1,
    },
  },
};

/** Type scale, straight from design/tokens/typography.css. */
export const type = {
  family: {
    body: "'Instrument Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    heading: "'Source Serif 4', Georgia, 'Times New Roman', serif",
    icon: "'Material Symbols Rounded'",
  },
  weight: {
    regular: 400,
    emphasis: 500,
    wordmark: 600,
  },
  size: {
    titleDesktop: 32,
    titlePhone: 26,
    stat: 18,
    cardTitle: 15,
    body: 12.5,
    chip: 12,
    label: 11.5,
    small: 11,
    meta: 10.5,
    tab: 10,
    badge: 10,
  },
  lineHeight: {
    tight: 1,
    stat: 1.1,
    title: 1.3,
    body: 1.4,
    row: 1.35,
  },
  tracking: {
    title: -0.01,
    label: 0.08,
    wordmark: 0.16,
  },
  icon: {
    tab: 21,
    rail: 18,
    header: 17,
    inline: 16,
    chip: 14,
  },
} as const;

/** design/tokens/layout.css's --js-space-1..10 (px). */
export const space = {
  "1": 2,
  "2": 6,
  "3": 8,
  "4": 9,
  "5": 10,
  "6": 12,
  "7": 16,
  "8": 18,
  "9": 24,
  "10": 32,
} as const;

/**
 * Phone page padding. --js-page-pad-phone in the vendored CSS is still the
 * v1.0 value (design/DISCREPANCIES.md #2) — the mock and reference build
 * win: top = safe-area-inset-top + topBase, sides on both edges, bottom
 * clears the mic/tab bar. Callers add the device's safe-area inset to
 * `topBase` themselves (useSafeAreaInsets is a hook; this file is not).
 */
export const pagePadPhone = {
  topBase: 22,
  sides: 20,
  bottom: 120,
} as const;
export const pagePadDesktop = {
  top: 24,
  sides: 32,
  bottom: 80,
} as const;

export const radius = {
  card: 10,
  control: 8,
  tag: 5,
  seg: 9,
  round: "50%",
} as const;

/** Backdrop blur radius (web `backdrop-filter: blur(Npx)`; native has no
 * equivalent — components fall back to the surface's opacity alone). */
export const blur = {
  card: 20,
  bar: 24,
} as const;

/**
 * Fixed-size controls (px). `habit`/`habitCompact` are overridden from the
 * mock/reference (design/DISCREPANCIES.md #3) — the vendored CSS still says
 * 36/34 — and `labelCol` is 60 where the pack says 48, because V2.1's
 * SECTION label does not fit 48 (design/DISCREPANCIES.md #20).
 */
export const sizes = {
  iconBtn: 32,
  iconBtnCard: 36,
  mic: 44,
  micLive: 42,
  habit: 34,
  habitCompact: 32,
  checkbox: 15,
  dot: 6,
  dotFeed: 7,
  badgeH: 16,
  labelCol: 60,
  ring: 56,
  barTrack: 8,
} as const;

/** CSS grid-template-columns strings — web `<Columns>` only; native computes
 * the same three ratios directly (flex has no grid-template equivalent). */
export const grid = {
  three: "1.3fr 1fr .95fr",
  two: "1.3fr 1fr",
  one: "1fr",
} as const;

export const motion = {
  fast: 80,
  base: 160,
  open: 200,
  ease: "cubic-bezier(.2,.7,.2,1)",
  pulseDuration: 1400,
  undoSeconds: 10,
} as const;

/** Breakpoints (px). Consumed only by theme/useLayout.ts (ADR-07) — no
 * other file may read these directly once the row-3 lint rule lands. */
export const bp = {
  tablet: 768,
  desktop: 1180,
} as const;

export const misc = {
  contentMax: 1500,
  railWidth: 200,
  barInset: 14,
  barHeight: 60,
  hoverLift: 0.08,
  pressedOpacity: 0.85,
  disabledOpacity: 0.45,
  toastRingBorder: "rgba(255,255,255,.4)",
  scrim: "rgba(28,26,22,.3)",
  scrimBlur: 4,
  scrollbarSize: 5,
  scrollbarThumb: "rgba(122,119,111,.3)",
} as const;

/** design/tokens.json's `iconName` block — the only part of that file that
 * is current (design/DISCREPANCIES.md #1). tools/gen-icons.mjs (row 3) adds
 * the mock's extra names on top of this set. */
export const iconNames = {
  today: "wb_sunny",
  tasks: "task_alt",
  brain: "neurology",
  life: "explore",
  agents: "hub",
  find: "search",
  settings: "settings",
  arrange: "grid_view",
  help: "help",
  themeToDark: "dark_mode",
  themeToLight: "light_mode",
  filter: "tune",
  more: "more_horiz",
  open: "chevron_right",
  send: "arrow_upward",
  voice: "mic",
  type: "keyboard",
} as const;

export const fonts = {
  body: Platform.select({ web: type.family.body, default: "InstrumentSans_400Regular" }) as string,
  bodyMedium: Platform.select({ web: type.family.body, default: "InstrumentSans_500Medium" }) as string,
  bodySemiBold: Platform.select({ web: type.family.body, default: "InstrumentSans_600SemiBold" }) as string,
  heading: Platform.select({ web: type.family.heading, default: "SourceSerif4_400Regular" }) as string,
  headingMedium: Platform.select({ web: type.family.heading, default: "SourceSerif4_500Medium" }) as string,
  mono: Platform.select({ ios: "Menlo", web: "ui-monospace", default: "monospace" }) as string,
} as const;
